{pkgs}: {
  deps = [
    pkgs.xvfb-run
    pkgs.scrot
    pkgs.zlib
    pkgs.openjpeg
    pkgs.libwebp
    pkgs.libtiff
    pkgs.libjpeg
    pkgs.libimagequant
    pkgs.lcms2
    pkgs.libGLU
    pkgs.libGL
    pkgs.tesseract
    pkgs.jq
    pkgs.xsimd
    pkgs.libxcrypt
    pkgs.tk
    pkgs.tcl
    pkgs.qhull
    pkgs.pkg-config
    pkgs.gtk3
    pkgs.gobject-introspection
    pkgs.ghostscript
    pkgs.freetype
    pkgs.ffmpeg-full
    pkgs.cairo
    pkgs.glibcLocales
  ];
}
